spring.application.name=product-management


server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=9a67279f10b32531a3e205f1299c0a481c1ae04c3519db83042183223a91932341f043e25a4741c5c9fa459f3abff9f7f5e57a5d738125431e477436d009a610
jwt.expiration-ms=86400000

# Logging Configuration
logging.level.com.assessment.product=INFO
logging.level.org.springframework.security=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
